dev:
    app_function: app.app
    aws_region: us-east-1
    profile_name: default
    project_name: asana-sync
    runtime: python3.6
    s3_bucket: unidata-python
    memory_size: 128
    keep_warm: true
    keep_warm_expression: "rate(4 minutes)"
    tags:
        Group: Python
        Project: AsanaBot
    manage_roles: false
    role_name: AsanaSync
    lambda_description: "Sync GitHub issues to Asana (using Zappa)"
    apigateway_description: "Sync GitHub issues to Asana (using Zappa)"
