name: Deploy Asanabot

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    environment: AWS

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS
      run: make deploy
